[package]
name = "kernel"
version = "0.0.0"
authors = ["Jerome Rasky <jerome@rasky.co>"]

[lib]
path = "src/kernel.rs"
crate-type = ["staticlib"]

[dependencies]
rlibc = "*"
spin = "*"
elfloader = "*"
log = { path = "lib/log" }
paging = { path = "lib/paging" }

[target]
custom_unwind_resume = {}
