[package]
name = "kernel"
version = "0.0.0"
authors = ["Jerome Rasky <jerome@rasky.co>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "*"
spin = "*"
log = {git = "https://github.com/jrasky/log.git", features = ["freestanding"]}
