[package]
name = "memory"
version = "0.1.0"
authors = ["Jerome Rasky <jyrome.112@gmail.com>"]

[dependencies]
spin = "*"
constants = { path = "../constants" }
log = { version = "*", default-features = false, features = ["nightly"]}
