[package]
name = "user"
version = "0.1.0"
authors = ["Jerome Rasky <jyrome.112@gmail.com>"]
build = "build.rs"

[dependencies]
log = { version = "*", default-features = false, features = ["nightly"] }

[build-dependencies]
nasm-rs = { git = "https://github.com/jrasky/nasm-rs" }
